tests/run now fails when at least one test fails

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -25,12 +25,12 @@ else
 fi
 
 # run
-find . -name '*.sh' | xargs "$morbig" --continue-after-error --as simple
+find . -name '*.sh' -exec "$morbig" --continue-after-error --as simple {} +
 
 # Count bad successes and good failures
 nrbadsuccess=$(find bad -name "$okpat" | wc -l)
 nrgoodfailures=$(find good -name "$kopat" | wc -l)
-nrunexpected=$(find good -name "*.expected" -exec $PROGDIR/checkexpectation {} \; | wc -l)
+nrunexpected=$(find good -name "*.expected" -exec ./checkexpectation {} \; | wc -l)
 
 # Summarize
 printf '=============================================================
@@ -43,22 +43,30 @@ Should succeed: OK: %3d  KO: %3d  OK but not as expected: %3d
        "$nrgoodfailures" \
        "$nrunexpected"
 
+# Return code. By default, success
+rc=0
+
 # Report the exact problematic tests
 if [ $nrgoodfailures -gt 0 ]
 then
     printf '** Failing tests that should succeed:\n'
     find good -name "$kopat" \
 	| sed "s|\(.*\).morbigerror|$PROGDIR/\1|"
+    rc=2
 fi
 if [ $nrunexpected -gt 0 ]
 then
     printf '** Succeded test with unexpected output:\n'
-    find good -name "*.expected" -exec $PROGDIR/checkexpectation {} \; \
-	| sed "s|\(.*\).morbigerror|$PROGDIR/\1|"
+    find good -name "*.expected" -exec ./checkexpectation {} \; \
+	| sed "s|\(.*\).expected|$PROGDIR/\1|"
+    rc=2
 fi
 if [ $nrbadsuccess -gt 0 ]
 then
     printf '** Succeeding tests that should fail:\n'
     find bad -name "$okpat" \
 	| sed "s|\(.*\).sjson|$PROGDIR/\1|"
+    rc=2
 fi
+
+exit $rc
