Untabify & re-indent tests runner

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -60,8 +60,8 @@ incr () {
 last_test_printed=
 printf_for_test () {
     if [ "$test" != "$last_test_printed" ]; then
-	last_test_printed=$test
-	printf '* %s\n' "$test"
+    last_test_printed=$test
+    printf '* %s\n' "$test"
     fi
     printf "$@"
 }
@@ -71,74 +71,74 @@ for category in good bad
 do
     for test in $(find "$category" -type f -name '*.sh' | sort -n)
     do
-	test=${test%.sh}
+        test=${test%.sh}
 
-	if [ \! -f "$test.sh" ]
-	then
-	    printf_for_test '[WARN] File `%s` does not exist or is not a file.
-         Did you create a test whose name contains a space?\n' "$test"
-	    continue
-	fi
+        if ! [ -f "$test.sh" ]
+        then
+            printf_for_test '[WARN] File `%s` does not exist or is not a file.
+Did you create a test whose name contains a space?\n' "$test"
+            continue
+        fi
 
-	open=
-	[ -e "$test.sh.open" ] && open=_open # Warning: the underscore matters.
+        open=
+        [ -e "$test.sh.open" ] && open=_open # Warning: the underscore matters.
 
-	incr ${category}${open}_total # eg. good_open_total or bad_total
+        incr ${category}${open}_total # eg. good_open_total or bad_total
 
-	if "$morbig" --as simple "$test.sh" 2>/dev/null
-	then
-	    case "$category""$open" in
-		bad)
-		    printf_for_test '[FAIL] Wrongly accepted: %s\n' "$test"
-		    incr bad_accepted
-		    ;;
-		bad_open)
-		    printf_for_test '[WARN] Open wrongly accepted: %s\n' "$test"
-		    incr bad_open_accepted
-		    ;;
+        if "$morbig" --as simple "$test.sh" 2>/dev/null
+        then
+            case "$category""$open" in
+                bad)
+                    printf_for_test '[FAIL] Wrongly accepted: %s\n' "$test"
+                    incr bad_accepted
+                    ;;
+                bad_open)
+                    printf_for_test '[WARN] Open wrongly accepted: %s\n' "$test"
+                    incr bad_open_accepted
+                    ;;
 
-		good*)
-		    if [ \! -f "$test.sh.expected" ]; then
-			printf_for_test '[WARN] Missing `.expected` file: %s\n' "$test"
-			incr good${open}_unexpected
+                good*)
+                    if ! [ -f "$test.sh.expected" ]; then
+                        printf_for_test '[WARN] Missing `.expected` file: %s\n' "$test"
+                        incr good${open}_unexpected
 
-		    elif ! diff "$test.sh.sjson" "$test.sh.expected" 2>&1 >/dev/null; then
-			if [ -n "$open" ]; then
-   		            printf_for_test '[WARN] Open with wrong output: %s\n' "$test"
-			else
-   		            printf_for_test '[FAIL] Wrong output: %s\n' "$test"
-			fi
-			if [ -n "$VERBOSE" ]; then
-			    echo '** .sh'
-			    cat "$test.sh"
-			    echo '** .sh.sjson'
-			    cat "$test.sh.sjson"
-			    echo '** .sh.expected'
-			    cat "$test.sh.expected"
-			fi
-			incr good${open}_unexpected
-		    else
-			incr good${open}_accepted
-		    fi
-	    esac
-	else
-	    case "$category" in
-		bad)
-		    incr bad${open}_rejected
-		    ;;
-		good)
-		    incr good${open}_rejected
-		    if [ -n "$open" ]; then
-			printf_for_test '[WARN] Open wrongly rejected: %s\n' "$test"
-		    else
-			printf_for_test '[FAIL] Wrongly rejected: %s\n' "$test"
-		    fi
- 		    if [ -n "$VERBOSE" ]; then
-			echo "** $test.sh"
-			cat "$test.sh"
-		    fi
-	    esac
-	fi
+                    elif ! diff "$test.sh.sjson" "$test.sh.expected" 2>&1 >/dev/null; then
+                        if [ -n "$open" ]; then
+                            printf_for_test '[WARN] Open with wrong output: %s\n' "$test"
+                        else
+                            printf_for_test '[FAIL] Wrong output: %s\n' "$test"
+                        fi
+                        if [ -n "$VERBOSE" ]; then
+                            echo '** .sh'
+                            cat "$test.sh"
+                            echo '** .sh.sjson'
+                            cat "$test.sh.sjson"
+                            echo '** .sh.expected'
+                            cat "$test.sh.expected"
+                        fi
+                        incr good${open}_unexpected
+                    else
+                        incr good${open}_accepted
+                    fi
+            esac
+        else
+            case "$category" in
+                bad)
+                    incr bad${open}_rejected
+                    ;;
+                good)
+                    incr good${open}_rejected
+                    if [ -n "$open" ]; then
+                        printf_for_test '[WARN] Open wrongly rejected: %s\n' "$test"
+                    else
+                        printf_for_test '[FAIL] Wrongly rejected: %s\n' "$test"
+                    fi
+                    if [ -n "$VERBOSE" ]; then
+                        echo "** $test.sh"
+                        cat "$test.sh"
+                    fi
+            esac
+        fi
     done
 done
 
@@ -173,10 +173,10 @@ printf '* Summary:
 
 if [ "$failed" -gt 0 ] || [ "$unexpected" -gt 0 ]; then
     if [ "$failed" -eq "$failed_open" ] && [ "$unexpected" -eq "$unexpected_open" ]; then
-	printf '[INFO] All failures are due to open bugs. This script will succeed.\n'
-	exit 0
+        printf '[INFO] All failures are due to open bugs. This script will succeed.\n'
+        exit 0
     else
-	exit 2
+        exit 2
     fi
 else
     printf "\n         ----------------\n"
